"""
Stock universe — 659+ tickers. March 2026.
"""

STOCK_UNIVERSE = [
    "AAOI", "ABVX", "ADEA", "AEHR", "AL", "AMAT", "AMPX", "ARM", "ASX", "ATEN",
    "AXTI", "BFH", "BKSY", "BKV", "BRX", "BSY", "BTSG", "BURL", "BW", "BWIN",
    "CARG", "CAVA", "CC", "CGNX", "CIEN", "CLDX", "CLMT", "CNK", "CNTA", "COHR",
    "COHU", "COIN", "CRC", "CVI", "CZR", "DAR", "DDOG", "DFTX", "DLR", "DNLI",
    "DNTH", "DOCN", "DYN", "ENPH", "EXAS", "FDX", "FIVE", "FORM", "FTNT", "GEV",
    "GLDD", "GLW", "GNRC", "GPRE", "GUSH", "GWRE", "ICHR", "INGM", "IOT", "JBL",
    "JCI", "JHG", "KEYS", "KIM", "KLAC", "KRMN", "KTB", "LASR", "LITE", "LRCX",
    "MASI", "MOD", "MRNA", "MRVL", "MTZ", "MU", "MUU", "NBIS", "NE", "NET",
    "NFLX", "NFXL", "NSA", "NTAP", "NVT", "NXT", "NYT", "OII", "OS", "OUT",
    "PARR", "PL", "PLAB", "POWI", "PWR", "RNG", "ROIV", "RSI", "SDRL", "SEDG",
    "SEE", "SEI", "SEM", "SNDK", "SPHR", "SRAD", "STX", "TER", "TGT", "TGTX",
    "TNDM", "TNGX", "TPH", "TWLO", "UCTT", "UE", "VAL", "VG", "VRE", "VRT",
    "VSAT", "WDC", "WIX", "WULF", "XPO", "YOU", "YPF", "ZD", "ZIM", "AA",
    "ADNT", "AGRO", "AMKR", "AMSC", "APLD", "ASTS", "ATO", "AVAV", "BE", "BKR",
    "CBRL", "CENX", "CF", "CLS", "FICO", "FLNC", "FRO", "FTAI", "GE", "GM",
    "GOOGL", "HIMS", "HOOD", "HUT", "INTU", "IONQ", "LNG", "MSTR", "NIO", "NRG",
    "ORCL", "PBR", "PLTR", "PNW", "PTEN", "QBTS", "RIVN", "RKLB", "RTX", "SU",
    "SYM", "TLN", "TTMI", "UMAC", "ESLT", "AAPL", "MSFT", "NVDA", "AMZN", "GOOG",
    "META", "TSLA", "BRK.B", "UNH", "JNJ", "XOM", "JPM", "V", "PG", "MA",
    "HD", "CVX", "LLY", "ABBV", "MRK", "PEP", "KO", "AVGO", "COST", "MCD",
    "TMO", "WMT", "DHR", "ACN", "ADBE", "LIN", "CRM", "AMD", "INTC", "TXN",
    "QCOM", "HON", "UPS", "LOW", "SBUX", "CAT", "GS", "BA", "IBM", "PLD",
    "BLK", "ISRG", "SYK", "MDT", "DE", "NOW", "ADP", "CB", "LMT", "AMGN",
    "MO", "AXP", "CI", "GILD", "ZTS", "T", "BKNG", "MDLZ", "ADI", "MMC",
    "VRTX", "CME", "SCHW", "TMUS", "REGN", "SO", "DUK", "BDX", "CSX", "EQIX",
    "EOG", "PNC", "USB", "AON", "ITW", "CL", "SHW", "FIS", "FISV", "NSC",
    "ICE", "APD", "HUM", "EL", "EW", "BSX", "MCO", "SPGI", "PSA", "AEP",
    "NEE", "EXC", "KMB", "MET", "D", "O", "ROST", "DG", "SRE", "ECL",
    "AFL", "PAYX", "TRV", "MSI", "PRU", "AIG", "ALL", "ED", "STZ", "WEC",
    "CMG", "HSY", "VLO", "PCAR", "KR", "FAST", "IDXX", "YUM", "OTIS", "ROK",
    "EFX", "EA", "CTSH", "ILMN", "AVB", "VRSK", "WELL", "NDAQ", "RMD", "HPQ",
    "MTB", "FITB", "ARE", "ANET", "CDNS", "SNPS", "MCHP", "MPWR", "SWKS", "PANW",
    "CRWD", "OKTA", "ZS", "TEAM", "WDAY", "ADSK", "ANSS", "PAYC", "SQ", "PYPL",
    "SHOP", "ABNB", "UBER", "LYFT", "DOCU", "ZM", "ROKU", "TTD", "SPOT", "MTCH",
    "PINS", "SNAP", "ETSY", "EBAY", "EXPE", "BK", "STT", "NTRS", "RF", "CFG",
    "HBAN", "CMA", "ALLY", "DFS", "COF", "SYF", "MS", "BX", "KKR", "APO",
    "TROW", "BEN", "IVZ", "CINF", "PGR", "WRB", "HIG", "AIZ", "RE", "LNC",
    "CARR", "TT", "PH", "IR", "XYL", "PNR", "DOV", "EMR", "ETN", "MMM",
    "NOC", "GD", "HII", "TDG", "HEI", "TXT", "LUV", "DAL", "UAL", "AAL",
    "ALK", "JBHT", "CHRW", "ODFL", "EXPD", "UNP", "CP", "CNI", "TRMB", "CMI",
    "WAB", "AGCO", "BG", "ADM", "MOS", "NTR", "FMC", "DD", "DOW", "LYB",
    "IFF", "ALB", "FCX", "NEM", "GOLD", "RGLD", "WPM", "COP", "PXD", "SLB",
    "HAL", "MPC", "PSX", "OXY", "DVN", "APA", "HES", "KMI", "WMB", "OKE",
    "EPD", "ET", "TRGP", "ENB", "CROX", "ONON", "MEDP", "OLED", "LFUS", "BRZE",
    "APPF", "SAIA", "GPI", "HUBG", "MTH", "IBP", "WSC", "MATX", "ATI", "ALGM",
    "CRUS", "SLAB", "SMPL", "SHAK", "BJRI", "TXRH", "WING", "CHEF", "PLAY", "CAKE",
    "BOOT", "ULTA", "OLLI", "BROS", "PZZA", "JACK", "KRUS", "ASO", "DKS", "HIBB",
    "SIG", "FND", "RH", "WGO", "THO", "LCII", "PATK", "BLDR", "TREX", "SSD",
    "AAON", "AZEK", "BECN", "CSWI", "UFPI", "GFF", "NSIT", "CDW", "SNX", "ARW",
    "LOGI", "HP", "DELL", "BOX", "DBX", "ESTC", "PD", "NEWR", "SMAR", "APPN",
    "INFA", "PATH", "AI", "AFRM", "UPST", "SOFI", "LC", "OPEN", "RDFN", "ZG",
    "Z", "EXPI", "COMP", "CBRE", "JLL", "COLD", "STAG", "FR", "EPR", "NNN",
    "ADC", "OHI", "SBRA", "MPW", "VICI", "GLPI", "WYNN", "MGM", "DKNG", "PENN",
    "FLUT", "ABG", "ACA", "ACIW", "ACLS", "ACVA", "ADMA", "ADUS", "AEIS", "AEO",
    "AER", "AGYS", "ALIT", "ALKT", "ALRM", "ALSN", "AMBA", "AMED", "AMPH", "AMPL",
    "AMRC", "AMWD", "ANF", "ANGO", "ANIP", "APAM", "APLE", "APLS", "APP", "ARCB",
    "ARCO", "ARLO", "AROC", "ARRY", "ASAN", "ASGN", "ASPN", "ASTE", "ATKR", "ATMU",
    "ATRC", "ATSG", "ATUS", "AVDX", "AVNS", "AVNT", "AVT", "AXSM", "AXTA", "AYX",
    "AZPN", "AZZ", "BC", "BCC", "BCRX", "BCPC", "BDC", "BHE", "BILL", "BJ",
    "BL", "BLBD", "BLKB", "BLMN", "BLTE", "BMI", "BMRN", "BRBR", "BRKR", "BSM",
    "BWA", "BWXT", "BYD", "BYND", "BZ", "CACC", "CADE", "CALX", "CAR", "CARS",
    "CASH", "CATY", "CBT", "CCOI", "CCS", "CDNA", "CDRE", "CDXS", "CEIX", "CELH",
    "CENT", "CENTA", "CERT", "CEVA", "CFB", "CHDN", "CHE", "CHH", "CHUY", "CLBT",
    "CLF", "CLH", "CNO", "CNX", "CNXC", "COLM", "COMM", "COOP", "CORT", "COTY",
    "COUR", "CR", "CRDO", "CRK", "CRL", "CRSR", "CSGS", "CTRE", "CTVA", "CUBI",
    "CVBF", "CVCO", "CVLT", "CWAN", "CWEN", "CWH", "CWK", "CXM", "CYTK", "URI",
    "SMCI", "AMC", "VZ", "KTOS", "IRDM", "FIX", "VST", "STNG", "HUBB", "MP",
    "STRL", "VMC",
]
